/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.8 public/models/ac_-_mclaren_p1/scene.gltf -o src/components1/Car1.jsx -r public
Author: DAVID.3D.ART (https://sketchfab.com/david3dart)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ac-mclaren-p1-747cedadc302451db61deafc85941395
Title: AC - Mclaren P1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car1(props) {
  const { nodes, materials } = useGLTF('/models/ac_-_mclaren_p1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.751}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-36.413, 14.321, 53.211]}>
            <mesh geometry={nodes.Rim_RF1_SUB1_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.Rim_RF1_SUB0_Rim_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Tyre_RF_2_Tyre_0.geometry} material={materials.Tyre} />
          </group>
          <group position={[-36.413, 14.318, 53.211]}>
            <group position={[1.805, 0.003, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Susp_Hub_RF_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
              <mesh geometry={nodes.g_Susp_Hub_RF_SUB0_Mechanicals_0.geometry} material={materials.Mechanicals} />
              <mesh geometry={nodes.g_Susp_Hub_RF_SUB2_Details_0.geometry} material={materials.Details} />
            </group>
          </group>
          <group position={[0, 5.561, 46.334]}>
            <group position={[0, 9.025, 27.484]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Bumper_F_SUB0_Carbon_Mult50_0.geometry} material={materials.Carbon_Mult50} />
              <mesh geometry={nodes.g_Bumper_F_SUB1_Matte_Black_0.geometry} material={materials.Matte_Black} />
            </group>
          </group>
          <mesh geometry={nodes.Brake_Disk_RR_2_Brake_Disk_0.geometry} material={materials.Brake_Disk} position={[-34.815, 15.459, -65.081]} />
          <mesh geometry={nodes.g_Susp_ALever_Top_LR_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[21.789, 20.856, -65.13]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.g_Susp_ALever_Top_RR_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[-21.789, 20.856, -65.13]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <group position={[34.814, 15.459, -65.081]}>
            <mesh geometry={nodes.Rim_LR1_SUB1_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.Rim_LR1_SUB0_Rim_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Tyre_LR_2_Tyre_0.geometry} material={materials.Tyre} />
          </group>
          <mesh geometry={nodes.g_Susp_ALever_Btm_LF_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[17.238, 8.651, 58.012]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <group position={[0, 47.608, -27.713]}>
            <group position={[0, -4.713, -16.102]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Window_B_SUB1_Windows_0.geometry} material={materials.Windows} />
              <mesh geometry={nodes.g_Window_B_SUB0_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
            </group>
          </group>
          <group position={[36.412, 14.318, 53.211]}>
            <group position={[-1.804, 0.003, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Susp_Hub_LF_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
              <mesh geometry={nodes.g_Susp_Hub_LF_SUB0_Mechanicals_0.geometry} material={materials.Mechanicals} />
              <mesh geometry={nodes.g_Susp_Hub_LF_SUB2_Details_0.geometry} material={materials.Details} />
            </group>
          </group>
          <group position={[36.412, 14.321, 53.211]}>
            <mesh geometry={nodes.Rim_LF1_SUB1_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.Rim_LF1_SUB0_Rim_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Tyre_LF_2_Tyre_0.geometry} material={materials.Tyre} />
          </group>
          <group position={[-18.103, 49.447, 8.908]} rotation={[-3.058, -1.125, 2.87]}>
            <group position={[-15.036, -4.19, -32.671]} rotation={[-0.668, 0.78, 0.399]}>
              <group position={[40.89, -4.636, -0.143]} rotation={[-0.589, 0.864, -2.812]}>
                <mesh geometry={nodes.polymsh_detached93_2_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} position={[36.296, 55.762, 3.481]} rotation={[0.835, -0.12, -3.01]} />
              </group>
              <group position={[34.676, -10.114, -9.261]} rotation={[-2.817, 0.365, 0.97]}>
                <mesh geometry={nodes.Cylinder7_SUB0_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
                <mesh geometry={nodes.Cylinder7_SUB1_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
              </group>
              <mesh geometry={nodes.polymsh6_2_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} position={[35.195, -7.118, -2.329]} rotation={[-3.09, 1.118, 1.772]} />
              <group position={[2.581, 9.63, 52.467]} rotation={[-2.205, 1.071, 0.776]}>
                <group position={[67.539, 43.784, -10.492]} rotation={[0.823, 0.003, 1.571]}>
                  <mesh geometry={nodes.polymsh_extracted_SUB0_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
                  <mesh geometry={nodes.polymsh_extracted_SUB1_Windows_0.geometry} material={materials.Windows} />
                </group>
                <mesh geometry={nodes.GEO_DOOR_L_SUB5_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB8_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB3_INT_Velvet_0.geometry} material={materials.INT_Velvet} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB4_INT_PLASTIC_Speakers_0.geometry} material={materials.INT_PLASTIC_Speakers} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB0_INT_carbon_0.geometry} material={materials.INT_carbon} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB7_INT_METAL_Aluminium_0.geometry} material={materials.INT_METAL_Aluminium} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB2_INT_PLASTIC_Black_0.geometry} material={materials.INT_PLASTIC_Black} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB6_INT_PLASTIC_Rubber_0.geometry} material={materials.INT_PLASTIC_Rubber} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB1_Matte_Black_0.geometry} material={materials.Matte_Black} />
                <mesh geometry={nodes.GEO_DOOR_L_SUB9_INT_Decals_REF_AT_GLOSS_0.geometry} material={materials.INT_Decals_REF_AT_GLOSS} />
              </group>
            </group>
            <mesh geometry={nodes.GEO_DOOR_RR_SUB4_Mirror_0.geometry} material={materials.Mirror} />
            <mesh geometry={nodes.GEO_DOOR_RR_SUB3_Windows_0.geometry} material={materials.Windows} />
            <mesh geometry={nodes.GEO_DOOR_RR_SUB2_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
            <mesh geometry={nodes.GEO_DOOR_RR_SUB5_Carbon_Mult50_0.geometry} material={materials.Carbon_Mult50} />
            <mesh geometry={nodes.GEO_DOOR_RR_SUB1_Carpaint_Black_0.geometry} material={materials.Carpaint_Black} />
            <mesh geometry={nodes.GEO_DOOR_RR_SUB0_Carpaint_0.geometry} material={materials.Carpaint} />
          </group>
          <group position={[18.105, 49.447, 8.908]} rotation={[-0.375, -1.01, -0.676]}>
            <group position={[-15.035, -12.047, 30.657]} rotation={[0.568, -0.847, 0.146]}>
              <group position={[40.891, -4.542, -0.957]} rotation={[2.021, 0.877, 2.428]}>
                <mesh geometry={nodes.polymsh_detached94_2_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} position={[-35.302, 55.719, -9.387]} rotation={[0.835, -0.12, -3.01]} />
              </group>
              <group position={[34.676, -12.02, 6.609]} rotation={[0.161, 0.509, 2.062]}>
                <mesh geometry={nodes.Cylinder6_SUB0_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
                <mesh geometry={nodes.Cylinder6_SUB1_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
              </group>
              <mesh geometry={nodes.polymsh54_2_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} position={[35.196, -7.469, 0.581]} rotation={[-0.379, 1.063, 1.755]} />
              <group position={[2.583, 21.761, -48.702]} rotation={[-0.698, 1.071, 2.365]}>
                <mesh geometry={nodes.GEO_DOOR_R1_SUB7_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB6_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB4_INT_Velvet_0.geometry} material={materials.INT_Velvet} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB5_INT_PLASTIC_Speakers_0.geometry} material={materials.INT_PLASTIC_Speakers} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB2_INT_carbon_0.geometry} material={materials.INT_carbon} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB0_INT_PLASTIC_Black_0.geometry} material={materials.INT_PLASTIC_Black} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB1_INT_PLASTIC_Rubber_0.geometry} material={materials.INT_PLASTIC_Rubber} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB3_Matte_Black_0.geometry} material={materials.Matte_Black} />
                <mesh geometry={nodes.GEO_DOOR_R1_SUB8_INT_Decals_REF_AT_GLOSS_0.geometry} material={materials.INT_Decals_REF_AT_GLOSS} />
                <mesh geometry={nodes.polymsh_extracted11_SUB0_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
                <mesh geometry={nodes.polymsh_extracted11_SUB1_Windows_0.geometry} material={materials.Windows} />
              </group>
            </group>
            <mesh geometry={nodes.polymsh5_SUB2_Mirror_0.geometry} material={materials.Mirror} />
            <mesh geometry={nodes.polymsh5_SUB4_Windows_0.geometry} material={materials.Windows} />
            <mesh geometry={nodes.polymsh5_SUB5_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
            <mesh geometry={nodes.polymsh5_SUB3_Carbon_Mult50_0.geometry} material={materials.Carbon_Mult50} />
            <mesh geometry={nodes.polymsh5_SUB1_Carpaint_Black_0.geometry} material={materials.Carpaint_Black} />
            <mesh geometry={nodes.polymsh5_SUB0_Carpaint_0.geometry} material={materials.Carpaint} />
          </group>
          <group position={[-34.815, 15.458, -65.082]}>
            <group position={[1.821, 0.001, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Susp_Hub_RR_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
              <mesh geometry={nodes.g_Susp_Hub_RR_SUB0_Mechanicals_0.geometry} material={materials.Mechanicals} />
              <mesh geometry={nodes.g_Susp_Hub_RR_SUB2_Details_0.geometry} material={materials.Details} />
            </group>
          </group>
          <group position={[0, 23.05, 73.38]}>
            <mesh geometry={nodes.LIGHT_0_2_Headlights_0.geometry} material={materials.Headlights} position={[0, 2.544, 4.855]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
            <mesh geometry={nodes.LIGHT_1_2_Headlights_0.geometry} material={materials.Headlights} position={[0, -23.05, -73.38]} />
          </group>
          <mesh geometry={nodes.g_Susp_ALever_Btm_LR_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[15.638, 7.724, -69.881]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <group position={[0, 19.85, -81.616]} rotation={[-0.424, Math.PI / 2, 0]}>
            <group position={[32.681, -512.095, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.g_Wing_Guide_SUB0_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.g_Wing_Guide_SUB2_Plastics_0.geometry} material={materials.Plastics} />
              <mesh geometry={nodes.g_Wing_Guide_SUB1_Details_0.geometry} material={materials.Details} />
            </group>
            <group position={[0.016, 6.354, 0]}>
              <group position={[-2.64, 1.336, 0]} rotation={[0, 0, -0.469]}>
                <group rotation={[0, 0, 0.904]}>
                  <mesh geometry={nodes.g_Wing_SUB1_Chrome_0.geometry} material={materials.Chrome} />
                  <mesh geometry={nodes.g_Wing_SUB3_Details_0.geometry} material={materials.Details} />
                  <mesh geometry={nodes.g_Wing_SUB2_Carpaint_0.geometry} material={materials.Carpaint} />
                  <mesh geometry={nodes.g_Wing_SUB0_Matte_Black_0.geometry} material={materials.Matte_Black} />
                </group>
              </group>
              <mesh geometry={nodes.g_Wing_Turn_SUB0_Chrome_0.geometry} material={materials.Chrome} />
              <mesh geometry={nodes.g_Wing_Turn_SUB1_Plastics_0.geometry} material={materials.Plastics} />
            </group>
          </group>
          <mesh geometry={nodes.g_Susp_ALever_Top_LF_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[23.388, 20.921, 53.26]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.g_Susp_ALever_Btm_RR_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[-15.638, 7.724, -69.881]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <group position={[34.814, 15.458, -65.082]}>
            <group position={[-1.82, 0.001, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
              <mesh geometry={nodes.g_Susp_Hub_LR_SUB1_Brake_Caliper_0.geometry} material={materials.Brake_Caliper} />
              <mesh geometry={nodes.g_Susp_Hub_LR_SUB0_Mechanicals_0.geometry} material={materials.Mechanicals} />
              <mesh geometry={nodes.g_Susp_Hub_LR_SUB2_Details_0.geometry} material={materials.Details} />
            </group>
          </group>
          <mesh geometry={nodes.g_Susp_ALever_Btm_RF_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[-17.238, 8.651, 58.012]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <group position={[0, 5.306, -58.55]}>
            <mesh geometry={nodes.g_Diffuser_2_INT_carbon_0.geometry} material={materials.INT_carbon} position={[0, 4.384, -20.602]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Brake_Disk_LF_2_Brake_Disk_0.geometry} material={materials.Brake_Disk} position={[36.412, 14.321, 53.211]} />
          <group position={[14.275, 31.383, 60.943]} rotation={[0.482, 0.049, -0.084]}>
            <mesh geometry={nodes.GEO_WIPER3_2_Plastics_0.geometry} material={materials.Plastics} position={[-1.209, 0, 0.035]} rotation={[2.999, 0.382, 3.079]} />
            <group position={[-30.178, -4.1, -12.746]} rotation={[0.118, -0.627, 0.251]}>
              <group position={[-0.993, 0.184, -1.197]} rotation={[0.122, 0, 0]}>
                <mesh geometry={nodes.polymsh_detached_2_Plastics_0.geometry} material={materials.Plastics} position={[-7.027, -58.698, -22.021]} rotation={[-0.671, 0.575, 0.188]} />
              </group>
              <mesh geometry={nodes.GEO_WIPER2_2_Plastics_0.geometry} material={materials.Plastics} position={[-0.36, -0.091, 1.037]} rotation={[-1.657, -0.044, 1.593]} />
            </group>
            <mesh geometry={nodes.GEO_WIPER1_2_Plastics_0.geometry} material={materials.Plastics} position={[-0.023, -0.444, -0.1]} rotation={[-1.53, 0.012, 1.5]} />
          </group>
          <group position={[0, 14.293, 53.211]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.g_Body_SUB6_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.g_Body_SUB7_Clear_Glass_0.geometry} material={materials.Clear_Glass} />
            <mesh geometry={nodes.g_Body_SUB3_Plastics_0.geometry} material={materials.Plastics} />
            <mesh geometry={nodes.g_Body_SUB13_Taillights_0.geometry} material={materials.Taillights} />
            <mesh geometry={nodes.g_Body_SUB0_Windows_0.geometry} material={materials.Windows} />
            <mesh geometry={nodes.g_Body_SUB12_Mechanicals_0.geometry} material={materials.Mechanicals} />
            <mesh geometry={nodes.g_Body_SUB10_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.g_Body_SUB4_Carpaint_Black_0.geometry} material={materials.Carpaint_Black} />
            <mesh geometry={nodes.g_Body_SUB5_Carbon_Mult50_0.geometry} material={materials.Carbon_Mult50} />
            <mesh geometry={nodes.g_Body_SUB1_Carpaint_Black_0.geometry} material={materials.Carpaint_Black} />
            <mesh geometry={nodes.g_Body_SUB2_Carpaint_0.geometry} material={materials.Carpaint} />
            <mesh geometry={nodes.g_Body_SUB11_Matte_Black_0.geometry} material={materials.Matte_Black} />
            <mesh geometry={nodes.g_Body_SUB9_Grid2_0.geometry} material={materials.Grid2} />
            <mesh geometry={nodes.g_Body_SUB8_Grid1_Mult70_0.geometry} material={materials.Grid1_Mult70} />
          </group>
          <group position={[0, 33.86, 46.538]}>
            <group position={[0, -8.01, 26.455]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes.GEO_HOOD_SUB2_Details_0.geometry} material={materials.Details} />
              <mesh geometry={nodes.GEO_HOOD_SUB0_Carpaint_0.geometry} material={materials.Carpaint} />
              <mesh geometry={nodes.GEO_HOOD_SUB1_Matte_Black_0.geometry} material={materials.Matte_Black} />
            </group>
          </group>
          <mesh geometry={nodes.Brake_Disk_RF_2_Brake_Disk_0.geometry} material={materials.Brake_Disk} position={[-36.413, 14.321, 53.211]} />
          <group position={[-34.815, 15.459, -65.081]}>
            <mesh geometry={nodes.Rim_RR1_SUB1_Details_0.geometry} material={materials.Details} />
            <mesh geometry={nodes.Rim_RR1_SUB0_Rim_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Tyre_RR_2_Tyre_0.geometry} material={materials.Tyre} />
          </group>
          <mesh geometry={nodes.g_Susp_ALever_Top_RF_2_Mechanicals_0.geometry} material={materials.Mechanicals} position={[-23.388, 20.921, 53.26]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Brake_Disk_LR_2_Brake_Disk_0.geometry} material={materials.Brake_Disk} position={[34.814, 15.459, -65.081]} />
          <mesh geometry={nodes.LIGHT_BRAKE_3_2_Taillights_0.geometry} material={materials.Taillights} />
          <mesh geometry={nodes.LIGHT_BRAKE_REAR_2_Taillights_0.geometry} material={materials.Taillights} />
          <mesh geometry={nodes.LIGHT_BRAKE_2_2_Taillights_0.geometry} material={materials.Taillights} />
          <mesh geometry={nodes.LIGHT_BRAKE_0_2_Taillights_0.geometry} material={materials.Taillights} />
          <mesh geometry={nodes.LIGHT_BRAKE_1_2_Taillights_0.geometry} material={materials.Taillights} />
          <mesh geometry={nodes.polymsh_extracted12_2_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
          <mesh geometry={nodes.Cylinder5_2_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} position={[37.689, 28.699, 40.368]} rotation={[-1.829, 0.261, 0.08]} />
          <mesh geometry={nodes.Cylinder4_2_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} position={[-37.689, 28.699, 40.368]} rotation={[-1.802, -0.006, -0.067]} />
          <group position={[14.092, 30.846, 17.766]} rotation={[0.217, 0, 0]}>
            <group position={[2.931, 0.032, 4.916]} rotation={[-0.018, -0.106, 0]}>
              <group position={[-17.023, -33.694, -16.231]} rotation={[-0.199, 0, 0]}>
                <mesh geometry={nodes.GEO_PAD_L_SUB1_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
                <mesh geometry={nodes.GEO_PAD_L_SUB0_INT_carbon_0.geometry} material={materials.INT_carbon} />
              </group>
            </group>
            <group position={[-2.773, 0.032, 4.916]} rotation={[-0.018, 0.088, 0]}>
              <group position={[-11.319, -33.694, -16.231]} rotation={[-0.199, 0, 0]}>
                <mesh geometry={nodes.GEO_PAD_R_SUB1_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
                <mesh geometry={nodes.GEO_PAD_R_SUB0_INT_carbon_0.geometry} material={materials.INT_carbon} />
              </group>
            </group>
            <mesh geometry={nodes.GEO_STEER1_SUB4_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
            <mesh geometry={nodes.GEO_STEER1_SUB6_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
            <mesh geometry={nodes.GEO_STEER1_SUB7_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
            <mesh geometry={nodes.GEO_STEER1_SUB1_INT_Skin_A_0.geometry} material={materials.INT_Skin_A} />
            <mesh geometry={nodes.GEO_STEER1_SUB0_INT_Velvet_0.geometry} material={materials.INT_Velvet} />
            <mesh geometry={nodes.GEO_STEER1_SUB2_INT_carbon_0.geometry} material={materials.INT_carbon} />
            <mesh geometry={nodes.GEO_STEER1_SUB3_INT_METAL_Aluminium_0.geometry} material={materials.INT_METAL_Aluminium} />
            <mesh geometry={nodes.GEO_STEER1_SUB5_INT_PLASTIC_Black_0.geometry} material={materials.INT_PLASTIC_Black} />
            <mesh geometry={nodes.GEO_STEER1_SUB8_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
          </group>
          <mesh geometry={nodes.polymsh_extracted10_2_Clear_Glass_0.geometry} material={materials.Clear_Glass} />
          <mesh geometry={nodes.LED_CHARGE_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_CHARGE_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_CHARGE_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_CHARGE_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_FUEL_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_FUEL_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_FUEL_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_FUEL_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.GEO_Seats_SUB5_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
          <mesh geometry={nodes.GEO_Seats_SUB4_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
          <mesh geometry={nodes.GEO_Seats_SUB0_INT_Skin_A_0.geometry} material={materials.INT_Skin_A} />
          <mesh geometry={nodes.GEO_Seats_SUB1_INT_Velvet_0.geometry} material={materials.INT_Velvet} />
          <mesh geometry={nodes.GEO_Seats_SUB2_INT_carbon_0.geometry} material={materials.INT_carbon} />
          <mesh geometry={nodes.GEO_Seats_SUB3_INT_PLASTIC_Black_0.geometry} material={materials.INT_PLASTIC_Black} />
          <mesh geometry={nodes.GEO_Seats_SUB6_INT_Cuciture_0.geometry} material={materials.INT_Cuciture} />
          <mesh geometry={nodes.CINTURE_OFF_SUB1_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
          <mesh geometry={nodes.CINTURE_OFF_SUB0_IN_Cinture_0.geometry} material={materials.IN_Cinture} />
          <mesh geometry={nodes.CINTURE_OFF_SUB2_INT_METAL_Aluminium_0.geometry} material={materials.INT_METAL_Aluminium} />
          <mesh geometry={nodes.CINTURE_ON_SUB2_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
          <mesh geometry={nodes.CINTURE_ON_SUB0_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
          <mesh geometry={nodes.CINTURE_ON_SUB1_IN_Cinture_0.geometry} material={materials.IN_Cinture} />
          <mesh geometry={nodes.polymsh_SUB9_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.polymsh_SUB2_INT_Decals_REF_GLOSS_0.geometry} material={materials.INT_Decals_REF_GLOSS} />
          <mesh geometry={nodes.polymsh_SUB7_INT_Decals_REF_spec_0.geometry} material={materials.INT_Decals_REF_spec} />
          <mesh geometry={nodes.polymsh_SUB10_Mirror_0.geometry} material={materials.Mirror} />
          <mesh geometry={nodes.polymsh_SUB11_INT_Decals_FLAT_0.geometry} material={materials.INT_Decals_FLAT} />
          <mesh geometry={nodes.polymsh_SUB8_INT_Carpet_0.geometry} material={materials.INT_Carpet} />
          <mesh geometry={nodes.polymsh_SUB5_INT_Velvet_0.geometry} material={materials.INT_Velvet} />
          <mesh geometry={nodes.polymsh_SUB1_INT_carbon_0.geometry} material={materials.INT_carbon} />
          <mesh geometry={nodes.polymsh_SUB6_INT_METAL_Aluminium_0.geometry} material={materials.INT_METAL_Aluminium} />
          <mesh geometry={nodes.polymsh_SUB0_INT_PLASTIC_Black_0.geometry} material={materials.INT_PLASTIC_Black} />
          <mesh geometry={nodes.polymsh_SUB4_INT_PLASTIC_Rubber_0.geometry} material={materials.INT_PLASTIC_Rubber} />
          <mesh geometry={nodes.polymsh_SUB3_Matte_Black_0.geometry} material={materials.Matte_Black} />
          <mesh geometry={nodes.polymsh_SUB12_INT_Decals_REF_AT_GLOSS_0.geometry} material={materials.INT_Decals_REF_AT_GLOSS} />
          <mesh geometry={nodes.DRS_Tag_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.DRS_Tag_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.DRS_Tag_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.IPAS_Tag_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.IPAS_Tag_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.IPAS_Tag_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.IPAS_Tag_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.DRS_Tag_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_BATTERY_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_BATTERY_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_BATTERY_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_BATTERY_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_WATER_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_WATER_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_WATER_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_WATER_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_OIL_0_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_OIL_1_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_OIL_2_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.LED_OIL_3_2_INT_DISPLAY_0.geometry} material={materials.INT_DISPLAY} />
          <mesh geometry={nodes.GEO_frontFender_2_Carpaint_0.geometry} material={materials.Carpaint} />
          <mesh geometry={nodes.polymsh_detached73_SUB0_Windows_0.geometry} material={materials.Windows} />
          <mesh geometry={nodes.polymsh_detached73_SUB1_Windows_alpha_0.geometry} material={materials.Windows_alpha} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ac_-_mclaren_p1/scene.gltf')
